version: '3.8'
services:

  postgres-primary:
    image: postgres:14-alpine
    container_name: postgres-primary
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hulumulu
      POSTGRES_DB: avito_db
      POSTGRES_PASSWORD: Qwerty123
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c wal_level=replica 
      -c hot_standby=on 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby_feedback=on;

  postgres-replica-1:
    image: postgres:14-alpine
    user: postgres
    restart: always
    healthcheck:
      test: 'pg_isready -U hulumulu --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: postgres-replica-1
    ports:
      - "5433:5433"
    environment:
      PGUSER: replicator
      PGPASSWORD: Qwerty123
    command: |
      bash -c "
      rm -rf /var/lib/postgresql/data/*
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=postgres-primary --port=5432
      do
      echo 'Waiting for primary to connect...'
      sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres -p 5433
      "
    depends_on:
      - avito-admin-api

  avito-admin-api:
    container_name: avito-admin-api
    build: ./backend/avito-admin-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres-primary
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-primary:5432/avito_db
      - SPRING_DATASOURCE_USERNAME=hulumulu
      - SPRING_DATASOURCE_PASSWORD=Qwerty123
      - AVITO_PRICES_SERVICES_URLS=http://avito-prices-api-primary:8081,http://avito-prices-api-replica-1:8082
      - DEMO_SERVER=true
      - AVITO_PRICES_API_STATUS_TIMEOUT=500 # Increase if servers are VERY far away apart from each other
  
  avito-prices-api-primary:
    container_name: avito-prices-api-primary
    build: ./backend/avito-prices-api
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - avito-admin-api
      - postgres-primary
    environment:
      - JAVA_TOOL_OPTIONS=-Dserver.port=8081
      - AVITO_ADMIN_API_URL=http://avito-admin-api:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-primary:5432/avito_db
      - SPRING_DATASOURCE_USERNAME=hulumulu
      - SPRING_DATASOURCE_PASSWORD=Qwerty123

  avito-prices-api-replica-1:
    container_name: avito-prices-api-replica-1
    build: ./backend/avito-prices-api
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - avito-admin-api
      - postgres-replica-1
    environment:
      - JAVA_TOOL_OPTIONS=-Dserver.port=8082
      - AVITO_ADMIN_API_URL=http://avito-admin-api:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-replica-1:5433/avito_db
      - SPRING_DATASOURCE_USERNAME=hulumulu
      - SPRING_DATASOURCE_PASSWORD=Qwerty123
  
  nginx:
    container_name: nginx
    build: ./frontend
    restart: always
    ports:
      - '80:80'
    depends_on:
      - avito-admin-api
