version: '3.8'
services:

  postgres_primary:
    image: postgres:14-alpine
    container_name: postgres_primary
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hulumulu
      POSTGRES_DB: avito_db
      POSTGRES_PASSWORD: Qwerty123
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c wal_level=replica 
      -c hot_standby=on 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby_feedback=on;

  postgres_replica_1:
    image: postgres:14-alpine
    user: postgres
    restart: always
    healthcheck:
      test: 'pg_isready -U hulumulu --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: postgres_replica_1
    ports:
      - "5433:5432"
    environment:
      PGUSER: replicator
      PGPASSWORD: Qwerty123
    command: |
      bash -c "
      rm -rf /var/lib/postgresql/data/*
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=postgres_primary --port=5432
      do
      echo 'Waiting for primary to connect...'
      sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    depends_on:
      - avito_admin_api

  avito_admin_api:
    container_name: avito_admin_api
    build: ./backend/avito-admin-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres_primary
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_primary:5432/avito_db
      - SPRING_DATASOURCE_USERNAME=hulumulu
      - SPRING_DATASOURCE_PASSWORD=Qwerty123
      - AVITO_PRICES_SERVICES_URLS=http://avito_prices_api_primary:8081,http://avito_prices_api_replica_1:8082
  
  avito_prices_api_primary:
    container_name: avito_prices_api_primary
    build: ./backend/avito-prices-api
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - avito_admin_api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_primary:5432/avito_db
      - SPRING_DATASOURCE_USERNAME=hulumulu
      - SPRING_DATASOURCE_PASSWORD=Qwerty123

  avito_prices_api_replica_1:
    container_name: avito_prices_api_replica_1
    build: ./backend/avito-prices-api
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - avito_prices_api_primary
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_primary:5432/avito_db
      - SPRING_DATASOURCE_USERNAME=hulumulu
      - SPRING_DATASOURCE_PASSWORD=Qwerty123
