version: '3.8'
services:

  postgres-primary:
    image: postgres:14-alpine
    container_name: postgres-primary
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hulumulu
      POSTGRES_DB: avito_db
      POSTGRES_PASSWORD: Qwerty123
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c wal_level=replica 
      -c hot_standby=on 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby_feedback=on

  postgres-replica-1:
    image: postgres:14-alpine
    user: postgres
    restart: always
    healthcheck:
      test: 'pg_isready -U hulumulu --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 10
    container_name: postgres-replica-1
    ports:
      - "5433:5433"
    environment:
      PGUSER: replicator
      PGPASSWORD: Qwerty123
    command: |
      bash -c '
      if [ ! "$$(ls -A /var/lib/postgresql/data)" ]; then
        until pg_basebackup --progress --pgdata=/var/lib/postgresql/data -R --slot=replication_slot1 --host=postgres-primary --port=5432 --checkpoint=fast
        do
        echo "Waiting for primary to connect..."
        sleep 1s
        done
        echo "Backup done, starting replica..."
      fi
      chmod 0700 /var/lib/postgresql/data
      postgres -p 5433
      '

  postgres-replica-2:
    image: postgres:14-alpine
    user: postgres
    restart: always
    healthcheck:
      test: 'pg_isready -U hulumulu --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 10
    container_name: postgres-replica-2
    ports:
      - "5434:5434"
    environment:
      PGUSER: replicator
      PGPASSWORD: Qwerty123
    command: |
      bash -c '
      if [ ! "$$(ls -A /var/lib/postgresql/data)" ]; then
        until pg_basebackup --progress --pgdata=/var/lib/postgresql/data -R --slot=replication_slot2 --host=postgres-primary --port=5432 --checkpoint=fast
        do
        echo "Waiting for primary to connect..."
        sleep 1s
        done
        echo "Backup done, starting replica..."
      fi
      chmod 0700 /var/lib/postgresql/data
      postgres -p 5434
      '

  avito-admin-api:
    container_name: avito-admin-api
    build: ./backend/avito-admin-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-primary:5432/avito_db
      - SPRING_DATASOURCE_USERNAME=hulumulu
      - SPRING_DATASOURCE_PASSWORD=Qwerty123
      - AVITO_PRICES_SERVICES_URLS=http://avito-prices-api-primary:8081,http://avito-prices-api-replica-1:8082,http://avito-prices-api-replica-2:8083
      - AVITO_PRICES_SERVICES_NAMES=Екатеринбург,Москва,Санкт-Петебрург
      - AVITO_PRICES_SERVICES_COORDS=56.838011,60.597474|55.791116,37.466952|59.886541,30.329361
      - DEMO_SERVER=true
      - AVITO_PRICES_API_STATUS_TIMEOUT=500 # Increase if servers are VERY far away apart from each other
      - AUTO_CACHE=false
      - USE_HASH=true
  
  avito-prices-api-primary:
    container_name: avito-prices-api-primary
    build: ./backend/avito-prices-api
    restart: always
    ports:
      - "8081:8081"
    environment:
      - JAVA_TOOL_OPTIONS=-Dserver.port=8081
      - AVITO_ADMIN_API_URL=http://avito-admin-api:8080
      - MAX_DATABASE_PING_IN_MILLIS=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-primary:5432/avito_db
      - SPRING_DATASOURCE_USERNAME=hulumulu
      - SPRING_DATASOURCE_PASSWORD=Qwerty123
      - SELF_URL=http://avito-prices-api-primary:8081
      - AVITO_PRICES_SERVICES_URLS=http://avito-prices-api-primary:8081,http://avito-prices-api-replica-1:8082,http://avito-prices-api-replica-2:8083
      - LOCATION=1
      - USE_HASH=true

  avito-prices-api-replica-1:
    container_name: avito-prices-api-replica-1
    build: ./backend/avito-prices-api
    restart: always
    ports:
      - "8082:8082"
    environment:
      - JAVA_TOOL_OPTIONS=-Dserver.port=8082
      - AVITO_ADMIN_API_URL=http://avito-admin-api:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-replica-1:5433/avito_db
      - MAX_DATABASE_PING_IN_MILLIS=50
      - SPRING_DATASOURCE_USERNAME=hulumulu
      - SPRING_DATASOURCE_PASSWORD=Qwerty123
      - SELF_URL=http://avito-prices-api-replica-1:8082
      - AVITO_PRICES_SERVICES_URLS=http://avito-prices-api-primary:8081,http://avito-prices-api-replica-1:8082,http://avito-prices-api-replica-2:8083
      - LOCATION=6
      - USE_HASH=true

  avito-prices-api-replica-2:
    container_name: avito-prices-api-replica-2
    build: ./backend/avito-prices-api
    restart: always
    ports:
      - "8083:8083"
    environment:
      - JAVA_TOOL_OPTIONS=-Dserver.port=8083
      - AVITO_ADMIN_API_URL=http://avito-admin-api:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-replica-2:5434/avito_db
      - MAX_DATABASE_PING_IN_MILLIS=50
      - SPRING_DATASOURCE_USERNAME=hulumulu
      - SPRING_DATASOURCE_PASSWORD=Qwerty123
      - SELF_URL=http://avito-prices-api-replica-2:8083
      - AVITO_PRICES_SERVICES_URLS=http://avito-prices-api-primary:8081,http://avito-prices-api-replica-1:8082,http://avito-prices-api-replica-2:8083
      - LOCATION=12
      - USE_HASH=true
  
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - '80:80'
  
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    ports:
      - '5173:5173'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
